#! /usr/bin/env python
#
# Python module example file
# Miguel A.L. Paraz <mparaz@mparaz.com>
#
# $Id: 5950a076783245c589678ec8e9098f5859d5d7fa $

import radiusd
import requests


def instantiate(p):
    print "*** instantiate ***"
    print p
    # return 0 for success or -1 for failure


def authenticate(p):
    print 'authenticate:', p
    return radiusd.RLM_MODULE_OK


def authorize(p):
    print "*** authorize ***"
    print
    radiusd.radlog(radiusd.L_INFO, '*** radlog call in authorize ***')
    print
    print p
    print
    print "radiusd.config:", radiusd.config
    print

# From NAS:
    username = ""
    password = ""
    from_nas = dict((x, y) for x, y in p)
    if from_nas['User-Name']:
        username = from_nas['User-Name']
    if from_nas['User-Password']:
        password = from_nas['User-Password']
    print "From NAS username, password:", username, password

# Django API:
#TODO: Try-catch
    r = requests.get("http://127.0.0.1/api/v1/customers/?login=" +
                     username+"&password="+password)
    if not r.status_code == 200:
        return radiusd.RLM_MODULE_REJECT
    else:
        response = r.json()
        print "API response:", response

        radius_reply = dict()
        radius_config = {
            'Auth-Type': 'Python'
        }

        ip = str(response[0][u'ip_address'])
        if ip:
            print 'ip address:', ip
            radius_reply['Framed-IP-Address'] = ip

        print 'radius_reply: ', tuple(radius_reply.items())

        if len(response) > 0:
            return (radiusd.RLM_MODULE_OK, tuple(radius_reply.items()), tuple(radius_config.items()))
        else:
            return radiusd.RLM_MODULE_REJECT


def preacct(p):
    print "*** preacct ***"
    print p
    return radiusd.RLM_MODULE_OK


def accounting(p):
    print "*** accounting ***"
    radiusd.radlog(radiusd.L_INFO, '*** radlog call in accounting (0) ***')
    print
    print p
    return radiusd.RLM_MODULE_OK


def pre_proxy(p):
    print "*** pre_proxy ***"
    print p
    return radiusd.RLM_MODULE_OK


def post_proxy(p):
    print "*** post_proxy ***"
    print p
    return radiusd.RLM_MODULE_OK


def post_auth(p):
    print "*** post_auth ***"
    print p
    return radiusd.RLM_MODULE_OK


def recv_coa(p):
    print "*** recv_coa ***"
    print p
    return radiusd.RLM_MODULE_OK


def send_coa(p):
    print "*** send_coa ***"
    print p
    return radiusd.RLM_MODULE_OK


def detach():
    print "*** goodbye from example.py ***"
    return radiusd.RLM_MODULE_OK
