# Generated by Django 3.1 on 2020-09-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
