# Generated by Django 3.1 on 2020-09-24 17:33

import billing.networking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0004_router_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='title',
            field=models.CharField(blank=True, default=billing.networking.models.rand_name, max_length=255),
        ),
    ]
