# Generated by Django 3.1 on 2020-09-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('download_speed_kbps', models.IntegerField(default=0, verbose_name='Download speed (kbps)')),
                ('upload_speed_kbps', models.IntegerField(default=0, verbose_name='Upload speed (kbps)')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
