# Generated by Django 3.1 on 2020-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internettariff',
            name='download_speed_kbps',
            field=models.PositiveIntegerField(default=0, verbose_name='Download speed (kbps)'),
        ),
        migrations.AlterField(
            model_name='internettariff',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='internettariff',
            name='title',
            field=models.CharField(default='Internet tariff', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='internettariff',
            name='upload_speed_kbps',
            field=models.PositiveIntegerField(default=0, verbose_name='Upload speed (kbps)'),
        ),
    ]
