# Generated by Django 3.1 on 2020-09-18 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_auto_20200918_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internettariff',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
