# Generated by Django 3.1 on 2020-09-24 17:33

import billing.tariff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_auto_20200919_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internettariff',
            name='title',
            field=models.CharField(default=billing.tariff.models.rand_name, max_length=255, unique=True),
        ),
    ]
