# Generated by Django 3.1 on 2020-09-25 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_auto_20200924_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internettariff',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
