# Generated by Django 3.1 on 2020-08-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200817_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='login',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
