# Generated by Django 3.1 on 2020-09-17 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200917_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
