# Generated by Django 3.1 on 2020-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200917_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Finance transaction', 'verbose_name_plural': 'Finance transactions'},
        ),
        migrations.AddField(
            model_name='customer',
            name='last_online',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
