# Generated by Django 3.1 on 2020-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200917_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
