# Generated by Django 3.1 on 2020-09-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_router_description'),
        ('customer', '0011_auto_20200917_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_online_router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='networking.router'),
        ),
    ]
