# Generated by Django 3.1 on 2020-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200917_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
