# Generated by Django 3.1 on 2020-09-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_auto_20200918_1243'),
        ('customer', '0015_customer_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.internettariff'),
        ),
    ]
