# Generated by Django 3.1 on 2020-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20200918_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='system',
            field=models.BooleanField(default=False, verbose_name='System transaction'),
        ),
    ]
