# Generated by Django 3.1 on 2020-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Customer #1268', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='login',
            field=models.CharField(default='user', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='pass', max_length=255),
        ),
    ]
