# Generated by Django 3.1 on 2020-09-24 17:09

import billing.customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20200924_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default=billing.customer.models.rand_name, max_length=255),
        ),
    ]
