# Generated by Django 3.1 on 2020-09-24 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20200924_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
