# Generated by Django 3.1 on 2020-10-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20200925_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_online_dhcp',
            field=models.BooleanField(default=False),
        ),
    ]
