# Generated by Django 3.1 on 2020-10-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_customer_last_online_dhcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_online_login',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='login',
            field=models.CharField(default='user', max_length=255, unique=True, verbose_name='Login or MAC address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='pass', help_text='Leave empty for DHCP', max_length=255),
        ),
    ]
